projeto/accounts/urls.py
from django.urls import path
from ..accounts import views as v

app_name = 'accounts'
urlpatterns = [
    path('login/', v.user_login, name='user_login'),
    path('new_user/', v.CreateUser.as_view(), name='new_user'),
]

projeto/core/urls.py
from django.urls import path

from ..core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

projeto/jogo/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views as v

app_name = 'jogo'


urlpatterns = [
    path('', v.index, name='index'),
    path('room/', v.room_view, name='room'),
    path('gameplay', RedirectView.as_view(pattern_name='index'), name='gameplay'),
]

projeto/urls.py
from django.contrib.auth.views import logout_then_login
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
# carregando arquivos estaticos no deploy: https://tutorial.djangogirls.org/pt/deploy/


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('projeto.core.urls')),
    path('logout/', logout_then_login, name='logout'),
    path('user/', include('projeto.accounts.urls')),
    path('jogo/', include('projeto.jogo.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

projeto/jogo/models.py
from django.db import models

# Create your models here.

projeto/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UsuarioForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

projeto/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from ..accounts.forms import UsuarioForm
from django.urls import reverse_lazy
from django.contrib.auth.signals import user_logged_out
from django.dispatch import receiver
from ..jogo import views as v


# Create your views here
def user_login(request):
    template_name = 'login.html'
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:index')
        else:
            messages.error(request, 'Usuário ou senha inválidos.')
            return render(request, 'login.html')
    return render(request, template_name, {})


class CreateUser(CreateView):
    template_name = 'user_form.html'
    form_class = UsuarioForm
    success_url = reverse_lazy('accounts:user_login')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['Titulo'] = "Cadastrar novo usuario"
        context['botao'] = 'Cadastrar'
        return context

projeto/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages


# Create your views here.
@login_required
def index(request):
    return render(request, 'index.html')

projeto/jogo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
import random
import string

# Create your views here.


class Cheap:
    cheap = []
    def __init__(self): 
        suites = ['♥️', '♣️', '♦️', '♠️']
        values = ['A','K','Q','J','10','9','8','7','6','5','4','3','2']
        self.cheap = [f'{suite}{value}' for suite in suites for value in values]
    
    def distribute_cards(self, num_cards, num_players):
        total_number_cards = num_cards * num_players
        if total_number_cards > len(self.cheap):
            raise ValueError("Não há cartas suficientes no baralho para distribuir para todos os jogadores.")

        random.shuffle(self.cheap) # embaralha o deck
        hands_players = [[] for _ in range(num_players)]
        for i in range(num_cards):
            for j in range(num_players):
                card = self.cheap.pop()
                hands_players[j].append(card)
        return hands_players




def index(request):
    num_of_players = 6
    num_of_cards = 6
    cheap = Cheap()
    hands_plays = cheap.distribute_cards(num_of_cards, num_of_players)
    return render(request, 'gameshow.html', {'hands_plays': hands_plays})


def room_view(request):
    return render(request, 'room.html')

projeto/accounts/templates/login.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Estoque</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>


    <style>
      body {
        margin: 0;
        padding: 0;
        background-color: #4CAF50;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }

      .login-container {
        width: 300px;
        height: 450px;
        background-color: white;
        border: 2px solid #000;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        position: relative;
      }

      .login-container::before {
        content: 'A';
        font-size: 80px;
        font-weight: bold;
        position: absolute;
        top: 0px;
        left: 20px;
        z-index: 1;
      }

      .login-container h2 {
        z-index: 2;
      }

      .login-form {
        z-index: 2;
        text-align: center;
      }

      .login-form input {
        width: 80%;
        padding: 10px;
        margin: 10px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
      }

      .login-form button {
        background-color: #007BFF;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-weight: bold;
      }

      .login-form button:hover {
        background-color: #0056b3;
      }
    </style>
  </head>
  <body>
      <div class="login-container">
          <h4>Login - Baralho FDP</h4>
          <form class="login-form" action="." method="post">
              {% csrf_token %}
              <input type="text" name="username" placeholder="Nome de usuário" required>
              <input type="password" name="password" placeholder="Senha" required>
              <button type="submit">Entrar</button>
          </form>
          {% for message in messages %}
          <div class="message_class">
            {% if 'success' in message.tags %}
              <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
            {% else %}
              <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
            {% endif %}
          </div>
          {% endfor %}
      </div>
  </body>
  <script>
    setTimeout(function() {
        var messages = document.querySelectorAll('.message_class');
        messages.forEach(function(message) {
            message.style.display = 'none';
        });
    }, 2000);
  </script>
</html>

projeto/accounts/templates/user_form.html
{% load static %}
{% load widget_tweaks %}

<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Estoque</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="col-md-6" style="padding: 30px;">
        <h5>Cadastro de novo Usuario</h5>
          <form method="POST" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group{% if field.errors %} has-error {% endif%}">
                <label for="{{ field.id_for_label }}">
                  {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                  {% else %}
                    {{ field.label }}
                  {% endif %}
                </label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                  <span class="text-muted">{{ error }}</span>
                {% endfor %}
              </div>
            {% endfor %}
            <div class="form-inline buttons">
              <a href="{% url 'accounts:user_login' %}" class="btn btn-danger">
                <i class="fa fa-times"></i>
                Cancelar
              </a>
              <div style="padding: 10px;">
                <button type="submit" class="btn btn-success">Cadastrar</button>
              </div>
            </div>
          </form>
    </div>
    <!-- Optional JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

projeto/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
{% load static %}
<!doctype html>
<html lang="">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>FPD Online</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    

    {% block css %}{% endblock css %}

  </head>
  <body>

    {% include "includes/nav.html" %}

    {% block content %}{% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <!--Bootstrap Js-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

projeto/core/templates/includes/nav.html
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark  fixed-top" style="background-color: #4CAF50;">
  <a class="navbar-brand" href="{% url 'core:index' %}">MENU</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto"></ul>

    {% if user.is_authenticated %}
      <ul class="navbar-nav px-3">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding-right: 30px;">ola, {{user.username}}</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">Minha conta</a>
            <a class="dropdown-item" href="{% url 'admin:index' %}">Gerente</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
          </div>
        </li>
      </ul>
    {% endif %}
  </div>
</nav>

projeto/core/templates/includes/pagination.html
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      <!--Laço que roda todas as paginas -->
      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}

          {% if page_obj.number == pg %}
            <li class="page-item"><a class="page-link" style="background-color: #575251; color: white;" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% endif %}

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}

        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>

projeto/core/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Bem-vindo!</h1>
    <p>Essa tela va ter alguma coisa no futuro ?.</p>
    <a href="{% url 'jogo:index' %}"><button type="button" class="btn btn-secondary">Amistoso</button></a>
    <a href="{% url 'core:disponivel_partida' %}"><button type="button" class="btn btn-success">Campeonato</button></a>
  </div>
</div>

{% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
{% endfor %}

{% endblock content %}

projeto/jogo/templates/gameshow.html
{% extends "base.html" %}

{% block content %}
<style>
    .players{
        display: flex;
        flex-direction: row;
        align-items: center;
    }
    .space_player{
        height: 100px; 
        width: 200px;
        background-color: red;
    }
    .my_space{
        position: fixed;
        padding-top: 23rem;
        padding-left: 32rem;
    }
</style>
<div class="div_pai">
    <div class="players">
        {% for player_hand in hands_plays %}
        <div style="padding: 5px;">
            <div class="space_player">
                <p>Jogador {{ forloop.counter }}: {{ player_hand|join:", " }}</p>
            </div> 
        </div>
        {% endfor %}
    </div>
    <div class="my_space">
        <div class="space_player">
            <p>Seu jogador: 3: ♦️8, ♥️K, ♥️Q, ♦️7, ♠️J, ♥️7</p>
        </div> 
    </div>
</div>
{% endblock content %}

projeto/jogo/templates/room.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h2>Pagina 3, espere alguem entrar para iniciar jogo</h2>
    <button type="button" id="room_id" class="btn btn-secondary">Gerar ID da sala</button>
    <a href=""><button type="button" class="btn btn-primary">Iniciar jogo</button></a>
  </div>
  <form>
    <input type="text" id="value_text" name="link_room" placeholder="Digite uma mensagem"/>
    <input id="username" type="hidden" name="username" value="{{request.user.username}}">
    <button type="button" id="btn" class="btn btn-success">Enviar</button>
  </form>
  <div id="messages"></div>
  {% for message in messages %}
  <div class="message_class" style="width: 60%;">
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
  </div>
  {% endfor %}
</div>
<script>

  // recebe mensagem do backend via websocket e exibe na div messages
  let url = `ws://${window.location.host}/ws/socket-server/` // cuidado com esse endereço local
  const chatSocket = new WebSocket(url)
  chatSocket.onmessage = function(e){
    let data = JSON.parse(e.data)
    console.log(data.message)
    if(data.type === 'chat'){
      console.log(data.message)
      let messages = document.getElementById('messages')
      messages.insertAdjacentHTML(
        'beforeend', 
        `<div>
            <p>${data.message}<p>
        </div>`
      )
    }
  }

  // Envia mensagem ao backend via websocket
  const username = document.getElementById('username')
  let button = document.getElementById('btn')
  const message = document.getElementById('value_text')
  button.addEventListener('click', function() {
    if(message.value != ""){
      chatSocket.send(JSON.stringify({
        'message': username.value + "- " + message.value
      }))
    }
  })

</script>
{% endblock content %}